<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 4 Análise de experimentos | R aplicado à suinocultura</title>
  <meta name="description" content="Esse material tem por objetivo dar suporte ao uso do R em análise de dados na área da suinocultura" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 4 Análise de experimentos | R aplicado à suinocultura" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="Figuras/capa4.jpg" />
  <meta property="og:description" content="Esse material tem por objetivo dar suporte ao uso do R em análise de dados na área da suinocultura" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 4 Análise de experimentos | R aplicado à suinocultura" />
  
  <meta name="twitter:description" content="Esse material tem por objetivo dar suporte ao uso do R em análise de dados na área da suinocultura" />
  <meta name="twitter:image" content="Figuras/capa4.jpg" />

<meta name="author" content="Marcio Valk" />


<meta name="date" content="2020-09-22" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="visu.html"/>
<link rel="next" href="rmd.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R aplicado a suinocultura</a></li>

<li class="divider"></li>
<li><a href="index.html#section"></a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Objetivos</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#sobre-os-autores"><i class="fa fa-check"></i>Sobre os autores</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tuto.html"><a href="tuto.html"><i class="fa fa-check"></i><b>1</b> Tutorial básico <code>R</code> e <code>RStudio</code></a><ul>
<li class="chapter" data-level="1.1" data-path="tuto.html"><a href="tuto.html#apresentação-da-linguagem-r"><i class="fa fa-check"></i><b>1.1</b> Apresentação da linguagem <code>R</code></a></li>
<li class="chapter" data-level="1.2" data-path="tuto.html"><a href="tuto.html#instalando-o-r"><i class="fa fa-check"></i><b>1.2</b> Instalando o <code>R</code></a></li>
<li class="chapter" data-level="1.3" data-path="tuto.html"><a href="tuto.html#instalando-o-rstudio"><i class="fa fa-check"></i><b>1.3</b> Instalando o RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="tuto.html"><a href="tuto.html#diretório-de-trabalho"><i class="fa fa-check"></i><b>1.4</b> Diretório de trabalho</a></li>
<li class="chapter" data-level="1.5" data-path="tuto.html"><a href="tuto.html#rstudio-cloud"><i class="fa fa-check"></i><b>1.5</b> RStudio Cloud</a></li>
<li class="chapter" data-level="1.6" data-path="tuto.html"><a href="tuto.html#instalação-de-pacotes"><i class="fa fa-check"></i><b>1.6</b> Instalação de pacotes</a><ul>
<li class="chapter" data-level="1.6.1" data-path="tuto.html"><a href="tuto.html#carregando-pacotes"><i class="fa fa-check"></i><b>1.6.1</b> Carregando pacotes</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="tuto.html"><a href="tuto.html#ajuda"><i class="fa fa-check"></i><b>1.7</b> Ajuda</a><ul>
<li class="chapter" data-level="1.7.1" data-path="tuto.html"><a href="tuto.html#google"><i class="fa fa-check"></i><b>1.7.1</b> Google</a></li>
<li class="chapter" data-level="1.7.2" data-path="tuto.html"><a href="tuto.html#stack-overflow"><i class="fa fa-check"></i><b>1.7.2</b> Stack Overflow</a></li>
<li class="chapter" data-level="1.7.3" data-path="tuto.html"><a href="tuto.html#help-do-r"><i class="fa fa-check"></i><b>1.7.3</b> Help do <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="tuto.html"><a href="tuto.html#funcionalidades-básicas"><i class="fa fa-check"></i><b>1.8</b> Funcionalidades básicas</a><ul>
<li class="chapter" data-level="1.8.1" data-path="tuto.html"><a href="tuto.html#operações-básicas"><i class="fa fa-check"></i><b>1.8.1</b> Operações básicas</a></li>
<li class="chapter" data-level="1.8.2" data-path="tuto.html"><a href="tuto.html#operadores-lógicos"><i class="fa fa-check"></i><b>1.8.2</b> Operadores lógicos</a></li>
<li class="chapter" data-level="1.8.3" data-path="tuto.html"><a href="tuto.html#tipos-de-dados"><i class="fa fa-check"></i><b>1.8.3</b> Tipos de dados</a></li>
<li class="chapter" data-level="1.8.4" data-path="tuto.html"><a href="tuto.html#valores-especiais"><i class="fa fa-check"></i><b>1.8.4</b> Valores especiais</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="tuto.html"><a href="tuto.html#estrutura-dos-dados"><i class="fa fa-check"></i><b>1.9</b> Estrutura dos dados</a><ul>
<li class="chapter" data-level="1.9.1" data-path="tuto.html"><a href="tuto.html#vetores"><i class="fa fa-check"></i><b>1.9.1</b> Vetores</a></li>
<li class="chapter" data-level="1.9.2" data-path="tuto.html"><a href="tuto.html#tarefa-2"><i class="fa fa-check"></i><b>1.9.2</b> Tarefa 2</a></li>
<li class="chapter" data-level="1.9.3" data-path="tuto.html"><a href="tuto.html#matrizes"><i class="fa fa-check"></i><b>1.9.3</b> Matrizes</a></li>
<li class="chapter" data-level="1.9.4" data-path="tuto.html"><a href="tuto.html#arrays"><i class="fa fa-check"></i><b>1.9.4</b> Arrays</a></li>
<li class="chapter" data-level="1.9.5" data-path="tuto.html"><a href="tuto.html#listas"><i class="fa fa-check"></i><b>1.9.5</b> Listas</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="tuto.html"><a href="tuto.html#programação-básica"><i class="fa fa-check"></i><b>1.10</b> Programação básica</a><ul>
<li class="chapter" data-level="1.10.1" data-path="tuto.html"><a href="tuto.html#variáveis"><i class="fa fa-check"></i><b>1.10.1</b> Variáveis</a></li>
<li class="chapter" data-level="1.10.2" data-path="tuto.html"><a href="tuto.html#laços-loops-for-e-while"><i class="fa fa-check"></i><b>1.10.2</b> Laços (<em>Loops</em>), <code>for</code> e <code>while</code></a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="tuto.html"><a href="tuto.html#funções"><i class="fa fa-check"></i><b>1.11</b> Funções</a></li>
<li class="chapter" data-level="1.12" data-path="tuto.html"><a href="tuto.html#operador-pipe"><i class="fa fa-check"></i><b>1.12</b> Operador <code>Pipe</code></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="import.html"><a href="import.html"><i class="fa fa-check"></i><b>2</b> Importando dados</a><ul>
<li class="chapter" data-level="2.1" data-path="import.html"><a href="import.html#dados-de-diferentes-formatos"><i class="fa fa-check"></i><b>2.1</b> Dados de diferentes formatos</a><ul>
<li class="chapter" data-level="2.1.1" data-path="import.html"><a href="import.html#dados-no-formato-.txt"><i class="fa fa-check"></i><b>2.1.1</b> Dados no formato <code>.txt</code></a></li>
<li class="chapter" data-level="2.1.2" data-path="import.html"><a href="import.html#dados-no-formato-.csv"><i class="fa fa-check"></i><b>2.1.2</b> Dados no formato <code>.csv</code></a></li>
<li class="chapter" data-level="2.1.3" data-path="import.html"><a href="import.html#dados-no-formato-.xls-e-.xlsx"><i class="fa fa-check"></i><b>2.1.3</b> Dados no formato <code>.xls</code> e <code>.xlsx</code></a></li>
<li class="chapter" data-level="2.1.4" data-path="import.html"><a href="import.html#dados-de-um-repositório-web"><i class="fa fa-check"></i><b>2.1.4</b> Dados de um repositório web</a></li>
<li class="chapter" data-level="2.1.5" data-path="import.html"><a href="import.html#dados-do-sas-spss-e-stata"><i class="fa fa-check"></i><b>2.1.5</b> Dados do <code>SAS</code>, <code>SPSS</code> e <code>STATA</code></a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="import.html"><a href="import.html#dataframes"><i class="fa fa-check"></i><b>2.2</b> Data Frames</a></li>
<li class="chapter" data-level="2.3" data-path="import.html"><a href="import.html#análise-exploratória"><i class="fa fa-check"></i><b>2.3</b> Análise exploratória</a><ul>
<li class="chapter" data-level="2.3.1" data-path="import.html"><a href="import.html#dados-faltantes"><i class="fa fa-check"></i><b>2.3.1</b> Dados faltantes</a></li>
<li class="chapter" data-level="2.3.2" data-path="import.html"><a href="import.html#fatores"><i class="fa fa-check"></i><b>2.3.2</b> Fatores</a></li>
<li class="chapter" data-level="2.3.3" data-path="import.html"><a href="import.html#medidas-de-tendência-central"><i class="fa fa-check"></i><b>2.3.3</b> Medidas de tendência central</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="import.html"><a href="import.html#gráficos-simples-scatter-plot"><i class="fa fa-check"></i><b>2.4</b> Gráficos simples (<code>scatter plot</code>)</a><ul>
<li class="chapter" data-level="2.4.1" data-path="import.html"><a href="import.html#plot-simples"><i class="fa fa-check"></i><b>2.4.1</b> Plot simples</a></li>
<li class="chapter" data-level="2.4.2" data-path="import.html"><a href="import.html#scatterplot"><i class="fa fa-check"></i><b>2.4.2</b> Scatterplot</a></li>
<li class="chapter" data-level="2.4.3" data-path="import.html"><a href="import.html#boxplot-simples"><i class="fa fa-check"></i><b>2.4.3</b> Boxplot simples</a></li>
<li class="chapter" data-level="2.4.4" data-path="import.html"><a href="import.html#box-plot-multiplas-váriáveis"><i class="fa fa-check"></i><b>2.4.4</b> Box plot multiplas váriáveis</a></li>
<li class="chapter" data-level="2.4.5" data-path="import.html"><a href="import.html#histogramas"><i class="fa fa-check"></i><b>2.4.5</b> Histogramas</a></li>
<li class="chapter" data-level="2.4.6" data-path="import.html"><a href="import.html#gráfico-de-densidades"><i class="fa fa-check"></i><b>2.4.6</b> Gráfico de densidades</a></li>
<li class="chapter" data-level="2.4.7" data-path="import.html"><a href="import.html#qqplot"><i class="fa fa-check"></i><b>2.4.7</b> QQplot</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="import.html"><a href="import.html#análise-estatística-de-dados---modelagem"><i class="fa fa-check"></i><b>2.5</b> Análise estatística de dados - Modelagem</a><ul>
<li class="chapter" data-level="2.5.1" data-path="import.html"><a href="import.html#regressão-linear-simples"><i class="fa fa-check"></i><b>2.5.1</b> Regressão linear simples</a></li>
<li class="chapter" data-level="2.5.2" data-path="import.html"><a href="import.html#regressão-múltipa"><i class="fa fa-check"></i><b>2.5.2</b> Regressão Múltipa</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visu.html"><a href="visu.html"><i class="fa fa-check"></i><b>3</b> Visualização de dados com o R</a><ul>
<li class="chapter" data-level="3.1" data-path="visu.html"><a href="visu.html#gráficos-com-o-ggplot2"><i class="fa fa-check"></i><b>3.1</b> Gráficos com o <code>ggplot2</code></a></li>
<li class="chapter" data-level="3.2" data-path="visu.html"><a href="visu.html#funções-geom-e-aes"><i class="fa fa-check"></i><b>3.2</b> Funções geom e aes</a><ul>
<li class="chapter" data-level="3.2.1" data-path="visu.html"><a href="visu.html#estética"><i class="fa fa-check"></i><b>3.2.1</b> Estética</a></li>
<li class="chapter" data-level="3.2.2" data-path="visu.html"><a href="visu.html#curva-de-tendência"><i class="fa fa-check"></i><b>3.2.2</b> Curva de tendência</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="visu.html"><a href="visu.html#segmentação-e-junção-de-gráficos-do-ggplot"><i class="fa fa-check"></i><b>3.3</b> Segmentação e junção de gráficos do <code>ggplot</code></a><ul>
<li class="chapter" data-level="3.3.1" data-path="visu.html"><a href="visu.html#segmentação"><i class="fa fa-check"></i><b>3.3.1</b> Segmentação</a></li>
<li class="chapter" data-level="3.3.2" data-path="visu.html"><a href="visu.html#junção-de-gráficos"><i class="fa fa-check"></i><b>3.3.2</b> Junção de gráficos</a></li>
<li class="chapter" data-level="3.3.3" data-path="visu.html"><a href="visu.html#salvando-um-gráfico"><i class="fa fa-check"></i><b>3.3.3</b> Salvando um gráfico</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="visu.html"><a href="visu.html#diferentes-tipos-de-gráficos"><i class="fa fa-check"></i><b>3.4</b> Diferentes tipos de gráficos</a><ul>
<li class="chapter" data-level="3.4.1" data-path="visu.html"><a href="visu.html#linhas-retas-horizontais-e-verticais"><i class="fa fa-check"></i><b>3.4.1</b> Linhas, retas horizontais e verticais</a></li>
<li class="chapter" data-level="3.4.2" data-path="visu.html"><a href="visu.html#box-plot"><i class="fa fa-check"></i><b>3.4.2</b> Box plot</a></li>
<li class="chapter" data-level="3.4.3" data-path="visu.html"><a href="visu.html#gráficos-de-barras"><i class="fa fa-check"></i><b>3.4.3</b> Gráficos de barras</a></li>
<li class="chapter" data-level="3.4.4" data-path="import.html"><a href="import.html#histogramas"><i class="fa fa-check"></i><b>3.4.4</b> Histogramas</a></li>
<li class="chapter" data-level="3.4.5" data-path="visu.html"><a href="visu.html#gráfico-de-séries-temporais"><i class="fa fa-check"></i><b>3.4.5</b> Gráfico de séries temporais</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ade.html"><a href="ade.html"><i class="fa fa-check"></i><b>4</b> Análise de experimentos</a><ul>
<li class="chapter" data-level="4.1" data-path="ade.html"><a href="ade.html#príncipios-e-definições-básicas"><i class="fa fa-check"></i><b>4.1</b> Príncipios e definições básicas</a></li>
<li class="chapter" data-level="4.2" data-path="ade.html"><a href="ade.html#experimentos-com-delineamento-inteiramente-casualizados-com-um-fator"><i class="fa fa-check"></i><b>4.2</b> Experimentos com delineamento inteiramente casualizados com um fator</a><ul>
<li class="chapter" data-level="4.2.1" data-path="ade.html"><a href="ade.html#granu"><i class="fa fa-check"></i><b>4.2.1</b> Granulometria ideal do grão de milho em ração para suínos</a></li>
<li class="chapter" data-level="4.2.2" data-path="ade.html"><a href="ade.html#replicação-e-randomização"><i class="fa fa-check"></i><b>4.2.2</b> Replicação e randomização</a></li>
<li class="chapter" data-level="4.2.3" data-path="ade.html"><a href="ade.html#exemplo-de-dados-de-delineamento-inteiramente-casualizados-com-um-fator"><i class="fa fa-check"></i><b>4.2.3</b> Exemplo de dados de delineamento inteiramente casualizados com um fator</a></li>
<li class="chapter" data-level="4.2.4" data-path="ade.html"><a href="ade.html#modelo-linear-para-delineamento-completamente-casualizados-com-um-fator"><i class="fa fa-check"></i><b>4.2.4</b> Modelo linear para delineamento completamente casualizados com um fator</a></li>
<li class="chapter" data-level="4.2.5" data-path="ade.html"><a href="ade.html#estimação"><i class="fa fa-check"></i><b>4.2.5</b> Estimação</a></li>
<li class="chapter" data-level="4.2.6" data-path="ade.html"><a href="ade.html#representção-matricial"><i class="fa fa-check"></i><b>4.2.6</b> Representção matricial</a></li>
<li class="chapter" data-level="4.2.7" data-path="ade.html"><a href="ade.html#mínimos-quadrados-matricial-com-o-r"><i class="fa fa-check"></i><b>4.2.7</b> Mínimos quadrados matricial com o <code>R</code></a></li>
<li class="chapter" data-level="4.2.8" data-path="ade.html"><a href="ade.html#função-lm"><i class="fa fa-check"></i><b>4.2.8</b> Função <code>lm()</code></a></li>
<li class="chapter" data-level="4.2.9" data-path="ade.html"><a href="ade.html#estimação-da-variância-sigma2"><i class="fa fa-check"></i><b>4.2.9</b> Estimação da variância <span class="math inline">\(\sigma^2\)</span></a></li>
<li class="chapter" data-level="4.2.10" data-path="ade.html"><a href="ade.html#teste-de-hipótese-para-efeito-dos-tratamentos"><i class="fa fa-check"></i><b>4.2.10</b> Teste de hipótese para efeito dos tratamentos</a></li>
<li class="chapter" data-level="4.2.11" data-path="ade.html"><a href="ade.html#análise-de-variância---anova"><i class="fa fa-check"></i><b>4.2.11</b> Análise de variância - ANOVA</a></li>
<li class="chapter" data-level="4.2.12" data-path="ade.html"><a href="ade.html#verificação-das-suposições-do-modelo-linear"><i class="fa fa-check"></i><b>4.2.12</b> Verificação das suposições do modelo linear</a></li>
<li class="chapter" data-level="4.2.13" data-path="ade.html"><a href="ade.html#fatores-e-delineamentos-fatoriais"><i class="fa fa-check"></i><b>4.2.13</b> Fatores e delineamentos fatoriais</a></li>
<li class="chapter" data-level="4.2.14" data-path="ade.html"><a href="ade.html#fatores-e-delineamentos-fatoriais-1"><i class="fa fa-check"></i><b>4.2.14</b> Fatores e delineamentos fatoriais</a></li>
<li class="chapter" data-level="4.2.15" data-path="ade.html"><a href="ade.html#fatores-e-delineamentos-fatoriais-2"><i class="fa fa-check"></i><b>4.2.15</b> Fatores e delineamentos fatoriais</a></li>
<li class="chapter" data-level="4.2.16" data-path="ade.html"><a href="ade.html#efeitos-principais"><i class="fa fa-check"></i><b>4.2.16</b> Efeitos principais</a></li>
<li class="chapter" data-level="4.2.17" data-path="ade.html"><a href="ade.html#efeitos-principais-1"><i class="fa fa-check"></i><b>4.2.17</b> Efeitos principais</a></li>
<li class="chapter" data-level="4.2.18" data-path="ade.html"><a href="ade.html#efeito-de-interação"><i class="fa fa-check"></i><b>4.2.18</b> Efeito de interação</a></li>
<li class="chapter" data-level="4.2.19" data-path="ade.html"><a href="ade.html#efeito-de-interação-1"><i class="fa fa-check"></i><b>4.2.19</b> Efeito de interação</a></li>
<li class="chapter" data-level="4.2.20" data-path="ade.html"><a href="ade.html#efeito-de-interação-2"><i class="fa fa-check"></i><b>4.2.20</b> Efeito de interação</a></li>
<li class="chapter" data-level="4.2.21" data-path="ade.html"><a href="ade.html#representação-por-modelo-de-regressão"><i class="fa fa-check"></i><b>4.2.21</b> Representação por modelo de regressão</a></li>
<li class="chapter" data-level="4.2.22" data-path="ade.html"><a href="ade.html#representação-por-modelo-de-regressão-ausência-de-interação"><i class="fa fa-check"></i><b>4.2.22</b> Representação por modelo de regressão (ausência de interação)</a></li>
<li class="chapter" data-level="4.2.23" data-path="ade.html"><a href="ade.html#representação-por-modelo-de-regressão-presença-de-interação"><i class="fa fa-check"></i><b>4.2.23</b> Representação por modelo de regressão (presença de interação)</a></li>
<li class="chapter" data-level="4.2.24" data-path="ade.html"><a href="ade.html#efeitos-principais-vs-efeito-de-interação"><i class="fa fa-check"></i><b>4.2.24</b> Efeitos principais <em>vs</em> efeito de interação</a></li>
<li class="chapter" data-level="4.2.25" data-path="ade.html"><a href="ade.html#efeitos-principais-vs-efeito-de-interação-1"><i class="fa fa-check"></i><b>4.2.25</b> Efeitos principais <em>vs</em> efeito de interação</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ade.html"><a href="ade.html#delineamento-fatorial-com-dois-fatores"><i class="fa fa-check"></i><b>4.3</b> Delineamento fatorial com dois fatores</a><ul>
<li class="chapter" data-level="4.3.1" data-path="ade.html"><a href="ade.html#delineamento-fatorial-com-dois-fatores-1"><i class="fa fa-check"></i><b>4.3.1</b> Delineamento fatorial com dois fatores</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="ade.html"><a href="ade.html#exemplo-da-bateria"><i class="fa fa-check"></i><b>4.4</b> Exemplo da bateria</a><ul>
<li class="chapter" data-level="4.4.1" data-path="ade.html"><a href="ade.html#exemplo-da-bateria-1"><i class="fa fa-check"></i><b>4.4.1</b> Exemplo da bateria</a></li>
<li class="chapter" data-level="4.4.2" data-path="ade.html"><a href="ade.html#exemplo-da-bateria-2"><i class="fa fa-check"></i><b>4.4.2</b> Exemplo da bateria</a></li>
<li class="chapter" data-level="4.4.3" data-path="ade.html"><a href="ade.html#exemplo-da-bateria-3"><i class="fa fa-check"></i><b>4.4.3</b> Exemplo da bateria</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="ade.html"><a href="ade.html#criando-um-planejamento-fatorial-com-dois-fatores-no-r"><i class="fa fa-check"></i><b>4.5</b> Criando um planejamento fatorial com dois fatores no <code>R</code></a><ul>
<li class="chapter" data-level="4.5.1" data-path="ade.html"><a href="ade.html#exemplo-da-bateria-4"><i class="fa fa-check"></i><b>4.5.1</b> Exemplo da bateria</a></li>
<li class="chapter" data-level="4.5.2" data-path="ade.html"><a href="ade.html#as-vantagens-dos-delineamentos-fatoriais"><i class="fa fa-check"></i><b>4.5.2</b> As vantagens dos delineamentos fatoriais</a></li>
<li class="chapter" data-level="4.5.3" data-path="ade.html"><a href="ade.html#para-casa"><i class="fa fa-check"></i><b>4.5.3</b> Para casa</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="ade.html"><a href="ade.html#anova-1-fator"><i class="fa fa-check"></i><b>4.6</b> ANOVA <em>1 Fator</em></a></li>
<li class="chapter" data-level="4.7" data-path="ade.html"><a href="ade.html#delineamento-inteiramente-casualizados"><i class="fa fa-check"></i><b>4.7</b> Delineamento inteiramente casualizados</a></li>
<li class="chapter" data-level="4.8" data-path="ade.html"><a href="ade.html#delineamento-em-blocos-ao-acaso"><i class="fa fa-check"></i><b>4.8</b> Delineamento em blocos ao acaso</a></li>
<li class="chapter" data-level="4.9" data-path="ade.html"><a href="ade.html#fatorial"><i class="fa fa-check"></i><b>4.9</b> Fatorial</a></li>
<li class="chapter" data-level="4.10" data-path="ade.html"><a href="ade.html#parcela-subdividida"><i class="fa fa-check"></i><b>4.10</b> Parcela subdividida</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="rmd.html"><a href="rmd.html"><i class="fa fa-check"></i><b>5</b> Relatórios e artigos científicos com o rmarkdown</a><ul>
<li class="chapter" data-level="5.1" data-path="rmd.html"><a href="rmd.html#relatório-dinâmico-com-o-rmarkdown"><i class="fa fa-check"></i><b>5.1</b> Relatório dinâmico com o Rmarkdown</a></li>
<li class="chapter" data-level="5.2" data-path="rmd.html"><a href="rmd.html#relatórios-em-word-pdf-ou-html"><i class="fa fa-check"></i><b>5.2</b> Relatórios em word, pdf ou html</a></li>
<li class="chapter" data-level="5.3" data-path="rmd.html"><a href="rmd.html#apresentações-em-power-point"><i class="fa fa-check"></i><b>5.3</b> Apresentações em Power Point</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referências.html"><a href="referências.html"><i class="fa fa-check"></i>Referências</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R aplicado à suinocultura</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ade" class="section level1">
<h1><span class="header-section-number">Capítulo 4</span> Análise de experimentos</h1>
<div class="figure"><span id="fig:pigfofocapa"></span>
<img src="Figuras/pigfofocapa.jpeg" alt="Pig é Tech" width="90%" />
<p class="caption">
Figura 4.1: Pig é Tech
</p>
</div>
<p>Nesse capítulo vamos assumir que o delineamento, planejamento ou <em>design</em> do experimento foi adequado e que o experimento foi corretamente conduzido. Pretendemos aqui realizar a <strong>análise</strong> dos dados e fazer a <strong>interpretação</strong> dos testes estatísticos usados para avaliar os fatores que controlam um parâmetro ou um grupo de parâmetros. Esses múltiplos fatores de entrada podem ter sido manipulados para permitir avaliar seus efeitos na variável de saída ou resposta.</p>
<div id="príncipios-e-definições-básicas" class="section level2">
<h2><span class="header-section-number">4.1</span> Príncipios e definições básicas</h2>
<p>No livro de <span class="citation">Lawson (<a href="#ref-lawson2014" role="doc-biblioref">2014</a>)</span> temos um dicionário de termos técnicos que permite um melhor acompanhamento da leitura.</p>
<ul>
<li><strong>Experimento</strong> é uma ação em que o pesquisador altera pelo menos uma das variáveis em estudo e depois observa o efeito de suas ações através de medidas de uma característica do indivíduo (variável resposta). Exemplo: variável alterada - <em>quantidade de mineral na ração</em>; variável resposta - <em>ganho e peso</em>.</li>
</ul>
<blockquote>
<p><em>Observe que coleta de dados observacionais não é experimentação.</em></p>
</blockquote>
<ul>
<li><p><strong>Unidade Experimental</strong> (ou parcela) é a unidade/indivíduo ao qual o tratamento será aplicado. Em geral, na suinocultura a unidade experimental é um suino.</p></li>
<li><p><strong>Subamostra</strong>, <strong>subunidade</strong> ou <strong>unidade observacional</strong>. Quando a unidade experimental é dividida, após a ação ter sido tomada. Isso é chamado de subamostra ou subunidade. Por exemplo, se a <em>unidade experimental fosse uma leitegada</em>, poderia-se considerar, após o experimento realizado, medir o peso médio das leitegadas.</p></li>
</ul>
<blockquote>
<p><em>Às vezes, só é possível medir uma característica separadamente para cada subunidade; por esse motivo, são frequentemente chamadas de unidades observacionais. Medições em subamostras ou subunidades da mesma unidade experimental, são geralmente correlacionados e as estatísticas, como a média, devem ser calculadas antes da análise dos dados, ao invés de ser tratado como resultados independentes. Quando as subunidades podem ser consideradas independentes e existe interesse em determinar a variância nas subamostras, para não gerar nenhuma confusão no teste F para fatores de tratamento, o modelo misto deve ser usado em vez de simplesmente calcular a média das subamostras.</em></p>
</blockquote>
<ul>
<li><p><strong>Variável Independente</strong> (<em>Variável preditora, Tratamento ou Fator</em>) pode ser uma das variáveis em estudo que está sendo controlada durante o experimento, como nível, quantidade, genética. Objetivo é verificar qual o efeito que uma mudança nessa variável causa na variável resposta.</p></li>
<li><p><strong>Variável oculta</strong> (<em>Background Variable ou Lurking Variable</em>). Uma <em>Variável independente</em> também pode ser oculta, não controlada no experimento, mas que também pode ter efeito sobre a variável resposta. Ex: Temperatura. Em um experimento bem planejado o efeito dessa variável oculta deve estar acomodado nas demais variáveis não sendo determinante para a conclusão do estudo sobre as demais variáveis.</p></li>
<li><p><strong>Variável dependente</strong> (ou resposta, geralmente denotada por <span class="math inline">\(y\)</span>) é a característica daunidade experimental que é medida após cada realização do experimento. Em algumas situações podemos ter mais de uma variável resposta.</p></li>
<li><p><strong>Efeito</strong> é a mudança na resposta causada pela mudança em um fator ou em uma variável independente/preditora. Após a realização do experimento, a análise dos dados pode chegar a conclusão de que o efeito é estatisticamente significativo, no entanto é importante que o pesquisador tenha capacidade de dizer se esse efeito tem importância prática. Isso é chamado de <strong>Efeito prático</strong>.</p></li>
<li><p><strong>Repetições</strong> são duas ou mais realizações de um experimento com as mesmas configurações dos fatores ou variáveis independentes mas com diferentes unidades experimentais. As medidas da variável dependente podem variar entre repetições devido à mudanças nas variáveis ocultas e diferenças inerentes às unidades experimentais.</p></li>
<li><p><strong>Medidas repetidas</strong> refere-se à medidas duplicadas da mesma unidade experimental para a mesma realização de um experimento. Por exemplo, se a variável resposta for o <em>Peso</em>, realiza-se a pesagem duas vezes para eleminar algum possível viés do equipamento. É necessário fazer a média das medições e não tratar como duas variáveis respostas.</p></li>
<li><p><strong>Delineamento de Experimentos</strong> é uma coleção de experimentos ou execuções planejada antes da execução real. Nessa etapa são definidas a organização das unidades e a forma como estas receberão os tratamentos.</p></li>
<li><p><strong>Fator Confundidor</strong> surgem quando uma alteração que um experimentador faz em um fator, entre as execuções, causa uma alteração em outro fator. Ou seja, esse fator tem influência sobre a variável resposta e também sobre uma variável preditora.</p></li>
<li><p><strong>Fator de Vício</strong> resulta de uma ação do experimentador sobre uma variável independente no momento exato em que uma variável oculta (lurking variable) também muda. Dessa forma o efeito observado na variável resposta também pode ser devido a mudança na variável oculta, causando assim um viés.</p></li>
<li><p><strong>Erro Experimental</strong> é a variação ``natural´´ existente entre observações de unidades experimentais que receberam o mesmo tratamento. Essa variação pode ser devida à questões inerentes ao indivíduo ou pela falta de uniformidade na condução física do experimento, muita vezes por variáveis que não podem ser contrladas. O fato de ser chamado <em>“erro”</em> não quer dizer que devemos abandonar tudo. É importante que o erro experimental seja reduzido ao máximo para que se tenha maior confiabilidade nos resultados ao utilizar técnicas estatísticas.</p></li>
</ul>
<p>Com essas definições em mente, a diferença entre os <em>estudos observacionais</em> e os <em>experimentos</em> podem ser explicados com mais clareza. Em um estudo observacional, as variáveis (independentes e dependentes) são observadas sem qualquer tentativa de alterar ou controlar o valor dos fatores independentes. Portanto, quaisquer mudanças observadas na resposta, ou variável dependente, não podem necessariamente ser atribuídas à mudanças observadas nas variáveis independentes porque variáveis de fundo ou ocultas podem ser a causa. Em um experimento, no entanto, as variáveis independentes são propositalmente variadas e as execuções são conduzidas em uma maneira de equilibrar o efeito de quaisquer variáveis de fundo que mudam. Desta forma, a mudança média na resposta pode ser atribuída às mudanças feitas nas variáveis independentes.</p>
</div>
<div id="experimentos-com-delineamento-inteiramente-casualizados-com-um-fator" class="section level2">
<h2><span class="header-section-number">4.2</span> Experimentos com delineamento inteiramente casualizados com um fator</h2>
<p>Em um delineamento inteiramente casualizados com um fator, <em>N</em> unidades experimentais (suínos) são aleatóriamente divididas em <em>K</em> grupos. Cada grupo
fica então sujeito a um dos níveis ou valores únicos do fator de tratamento.
Se cada um dos <em>K</em> grupos possui <em>r</em> unidades experimentais, então harerá <em>r</em> réplicas de cada execução com o mesmo nível do fator de tratamento. Se <em>N</em> não for múltiplo de <em>K</em>, então será um número desigual de repetições de cada nível de fator.</p>
<p>Todos as demais variáveis independentes devem ser mantidas constantes para que não influenciem os efeitos desse fator. Este delineamento considera deve ser usado um fator em estudo e unidades experimentais homogêneas.</p>
<div id="granu" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Granulometria ideal do grão de milho em ração para suínos</h3>
<p>Em um estudo (hipotético) para determinar a granulometria ideal do grão de milho em ração para suínos, um lote homogêneo de <em>n=12</em> leitões foi dividido em <span class="math inline">\(k=3\)</span> grupos (<em>avisa o pesquisador que o tamanho da amostra é muito pequeno</em>). Cada grupo recebeu ração composta com milho de diferentes granulometria. Os diferentes tipos de granulometria foram obtidos triturando-se 1 Kg de milho em um triturador durante 5, 10 e 15 segundos. O peso dos leitões foi aferido antes do experimento e após 3 semanas. O <em>ganho de peso</em> é a variável resposta, o fator de tratamento é o tempo de trituração de 1 kg de milho e a unidade experimental é cada um dos 12 leitões envolvidos no experimento. Embora outros fatores possam afetar o desempenho dos animais, como os outros componentes da ração, eles são mantidos constantes para todos os animais ao longo do experimento.</p>
</div>
<div id="replicação-e-randomização" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Replicação e randomização</h3>
<p>A replicação e a randomização foram popularizadas por Fisher. Estes são os primeiras técnicas que se enquadram na categoria de <em>controle de erro</em>. A técnica de replicação exige que <em>r</em> suínos sejam testados para cada tipo de granulagem, em vez de um único animal. Por haver replicação das unidades experimentais em cada nível do fator de tratamento, a variância do erro experimental pode ser calculado a partir dos dados, e esta variação será comparada aos efeitos do tratamento. Se a variabilidade entre os tratamentos não é maior do que a variância do erro experimental, as diferenças entre tratamentos são provavelmente devidas às diferenças das unidades experimentais atribuídas a cada tratamento. Sem replicação, é impossível dizer se a diferença entre tratamentos são reais ou apenas uma manifestação aleatória atribuídas às unidades experimentais.</p>
<p>A divisão aleatória de unidades experimentais em grupos é chamada de aleatorização, e é o procedimento pelo qual a validade do experimento é garantida contra vieses causados por outras variáveis ocultas. Na granulagem do milho, a randomização do experimento evita variáveis ocultas, como a variabilidade na capacidade de metabolização dos suínos e sexo, por exemplo.</p>
<p>Quando as unidades experimentais são randomizadas para os níveis do fator de tratamento, um <em>teste de hipótese </em> para testar a hipótese de que o efeito do tratamento é zero, pode ser realizado. Um teste para testar a significância dos parâmetros de um modelo linear, normalmente usado na análise de dados experimentais, é uma boa abordagem.</p>
</div>
<div id="exemplo-de-dados-de-delineamento-inteiramente-casualizados-com-um-fator" class="section level3">
<h3><span class="header-section-number">4.2.3</span> Exemplo de dados de delineamento inteiramente casualizados com um fator</h3>
<p>Para dar sequência ao exemplo de granulometria ideal do grão de milho em ração para suínos vamos usar o <code>R</code> para construir um conjunto de dados aleatorizados com as caraterísticas descritas no exemplo. Nesse caso temos o fator tempo de moagem com 3 tempos de duração (<strong>níveis</strong>), (5, 10 e 15 segundos) e a ração é oferecida para 3 grupos de 4 suínos. Podemos exemplificar esse experimento usando o seguinte código do <code>R</code>.</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" title="1"><span class="kw">set.seed</span>(<span class="dv">732</span>)</a>
<a class="sourceLine" id="cb379-2" title="2">n=<span class="dv">12</span></a>
<a class="sourceLine" id="cb379-3" title="3">ri=<span class="dv">4</span></a>
<a class="sourceLine" id="cb379-4" title="4">fatores=<span class="kw">c</span>(<span class="st">&quot;T5&quot;</span>,<span class="st">&quot;T10&quot;</span>,<span class="st">&quot;T15&quot;</span>)</a>
<a class="sourceLine" id="cb379-5" title="5">k=<span class="kw">length</span>(fatores)</a>
<a class="sourceLine" id="cb379-6" title="6">temp=<span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;T5&quot;</span>,<span class="st">&quot;T10&quot;</span>,<span class="st">&quot;T15&quot;</span>),<span class="dt">each=</span>ri))  <span class="co"># níveis do fator tempo de trituração</span></a>
<a class="sourceLine" id="cb379-7" title="7">ind =<span class="st"> </span><span class="dv">1</span><span class="op">:</span>n  <span class="co"># Indivíduos de 1:12  (N=12)</span></a>
<a class="sourceLine" id="cb379-8" title="8"></a>
<a class="sourceLine" id="cb379-9" title="9">fa=<span class="kw">sample</span>(temp, n )          <span class="co"># aleatorização dos níveis do fator tempo</span></a>
<a class="sourceLine" id="cb379-10" title="10">indfa=<span class="kw">c</span>(<span class="kw">which</span>(fa<span class="op">==</span><span class="st">&quot;T5&quot;</span>),<span class="kw">which</span>(fa<span class="op">==</span><span class="st">&quot;T10&quot;</span>),<span class="kw">which</span>(fa<span class="op">==</span><span class="st">&quot;T15&quot;</span>))</a>
<a class="sourceLine" id="cb379-11" title="11">gp =<span class="ot">NULL</span></a>
<a class="sourceLine" id="cb379-12" title="12">gp[indfa]=<span class="st">  </span><span class="kw">c</span>(<span class="kw">rnorm</span>(ri,<span class="dv">40</span>,<span class="dv">1</span>),<span class="kw">rnorm</span>(ri,<span class="fl">40.3</span>,<span class="dv">1</span>),<span class="kw">rnorm</span>(ri,<span class="fl">42.7</span>,<span class="dv">1</span>)) <span class="co"># ganho de peso</span></a>
<a class="sourceLine" id="cb379-13" title="13"></a>
<a class="sourceLine" id="cb379-14" title="14">dados.g=<span class="kw">data.frame</span>(<span class="dt">individuo=</span>ind,<span class="dt">fator=</span>fa,<span class="dt">Ganho.de.Peso=</span>gp)</a>
<a class="sourceLine" id="cb379-15" title="15"><span class="kw">print</span>(dados.g,<span class="dt">row.names =</span> <span class="ot">FALSE</span>) </a></code></pre></div>
<pre><code>##  individuo fator Ganho.de.Peso
##          1   T15      40.97963
##          2   T10      41.27791
##          3   T15      44.52896
##          4    T5      41.82071
##          5   T10      40.93857
##          6   T10      41.39541
##          7    T5      39.42093
##          8   T15      42.75486
##          9   T15      43.16085
##         10    T5      39.81374
##         11   T10      39.85578
##         12    T5      39.63515</code></pre>
<p>Observando a variável resposta <em>Ganho.de.Peso</em> podemos ter uma média (geral), ou uma média para cada um dos níveis “T5”, “T10” e “T15”, as quais podemos chamar de <span class="math inline">\(m_5\)</span>, <span class="math inline">\(m_{10}\)</span> e <span class="math inline">\(m_{15}\)</span>. Apergunta natural aqui é a comparação entre <span class="math inline">\(m_5\)</span>, <span class="math inline">\(m_{10}\)</span> e <span class="math inline">\(m_{15}\)</span>. Se existir alguma diferença nessas
médias, teremos um indício de que alguama granulagem é mais adequada/eficiente para o ganho de peso. Para que possamos testar essas possíveis diferenças é mais interessante colocar o problema em forma de um modelo matemático.</p>
</div>
<div id="modelo-linear-para-delineamento-completamente-casualizados-com-um-fator" class="section level3">
<h3><span class="header-section-number">4.2.4</span> Modelo linear para delineamento completamente casualizados com um fator</h3>
<p>O modelo matemático para os dados de um delineamento completamente casualizados (DCC) com um fator, ou delineamento completamente aleatório, com um número igual ou desigual de repetições para cada nível de fator pode ser escrito como:</p>
<p><span class="math display" id="eq:mod1fator">\[\begin{equation}
Y_{ij}=\mu_i+\varepsilon_{ij}
 \tag{4.1}
\end{equation}\]</span></p>
<p>em que <span class="math inline">\(Y_{ij}\)</span> é a resposta para a <span class="math inline">\(j\)</span>-ésima unidade experimental sujeita à <span class="math inline">\(i\)</span>-ésima nível do fator de tratamento, <span class="math inline">\(i = 1,\dots,k\)</span>, <span class="math inline">\(j = 1,\dots,r_i\)</span>, e <span class="math inline">\(r_i\)</span> é o número de unidades experimentais ou replicações no nível <span class="math inline">\(i\)</span> do fator de tratamento. Ou seja, é possível que se tenha uma média diferente para cada nível <span class="math inline">\(i\)</span> do tratamento (<em>observe que para o exemplo da granulometria, cada um dos 12 leitões está representado nesse modelo</em> e <span class="math inline">\(\mu_1=m_5\)</span>, <span class="math inline">\(\mu_2=m_{10}\)</span> e <span class="math inline">\(\mu_3=m_{15}\)</span>). A distribuição dos erros experimentais, <span class="math inline">\(ij\)</span>, são mutuamente independentes devido à randomização e assumidas tendo distribuição normal. Assim, o problema da granulometria pode ser representado graficamente como na Figura <a href="ade.html#fig:figmus">4.2</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:figmus"></span>
<img src="R-aplicado-a-suinocultura_files/figure-html/figmus-1.png" alt="Distribuição dos tratamentos com diferentes médias no exemplo da granulometria " width="864" />
<p class="caption">
Figura 4.2: Distribuição dos tratamentos com diferentes médias no exemplo da granulometria
</p>
</div>
<p>Uma maneira alternativa de escrever o modelo <a href="ade.html#eq:mod1fator">(4.1)</a> é</p>
<p><span class="math display" id="eq:mod1fator2">\[\begin{equation}
Y_{ij}=\mu+\tau_i+\varepsilon_{ij}.
 \tag{4.2}
\end{equation}\]</span></p>
<p>Isso é chamado de <em>modelo de efeitos</em> e <span class="math inline">\(\tau_i\)</span>’s os são chamados de efeitos. O parâmetro <span class="math inline">\(\tau_i\)</span> representa a diferença entre a média de longo prazo de todos os experimentos possíveis no <span class="math inline">\(i\)</span>-ésimo nível do fator de tratamento e a média geral. Com a suposição de normalidade, <span class="math inline">\(Y_{ij}\sim N (\mu+\tau_i; \sigma^2)\)</span> ou <span class="math inline">\(\varepsilon_{ij} \sim N(0; \sigma^2)\)</span>. A média no <span class="math inline">\(i\)</span>-ésimo nível do fator de tratamento é representado por</p>
<p><span class="math display" id="eq:meanfac">\[\begin{equation}
\overline{y}_{i.}=\frac{1}{r_{i}} \sum_{j=1}^{r_{i}} y_{i j}
 \tag{4.3}
\end{equation}\]</span>
em que o <span class="math inline">\(r_i\)</span> é o número de animais no i-ésimo grupo, ou seja, <span class="math inline">\(n=\sum r_i\)</span>, e a grande média (média de todas as observações) é dada por</p>
<p><span class="math display" id="eq:granmean">\[\begin{equation}
\overline{y}_{..}=\frac{1}{k} \sum_{i=1}^{k} \overline{y}_{i.}=\frac{1}{n} \sum_{i=1}^{k} \sum_{j=1}^{r_{i}} y_{i j}
 \tag{4.4}
\end{equation}\]</span></p>
</div>
<div id="estimação" class="section level3">
<h3><span class="header-section-number">4.2.5</span> Estimação</h3>
<p>Usando o método de <em>máxima verossimilhança</em>, que é equivalente ao método dos mínimos quadrados ordinários (MQO) com essas suposições, as estimativas das médias das células são obtidas minimizando a <em>soma dos quadrados dos erros</em> (<span class="math inline">\(SQE\)</span>)</p>
<p><span class="math display" id="eq:sqe">\[\begin{equation}
SQE=\sum_{i=1}^{k} \sum_{j=1}^{r_{i}}\left(y_{i j}-\mu_{i}\right)^{2}.
 \tag{4.5}
\end{equation}\]</span></p>
<p>Isso é feito tomando derivados parciais de <span class="math inline">\(SQE\)</span> em relação a cada média da célula, igualando a zero e resolvendo cada equação teremos</p>
<p><span class="math display">\[\frac{\partial SQE}{\partial \mu_{i}}=-2 \sum_{i=1}^{k} \sum_{j=1}^{r_{i}}\left(y_{i j}-\mu_{i}\right)=0\]</span></p>
<p>Como resultados dessa operação obtemos, para a equação <a href="ade.html#eq:mod1fator">(4.1)</a>, o estimador</p>
<p><span class="math display">\[\hat{\mu}_{i}=\overline{y}_{i \cdot}\]</span></p>
<p>e para a equação <a href="ade.html#eq:mod1fator2">(4.2)</a></p>
<p><span class="math display">\[\widehat{\mu + \tau_{i}}=\overline{y}_{i \cdot}\]</span></p>
</div>
<div id="representção-matricial" class="section level3">
<h3><span class="header-section-number">4.2.6</span> Representção matricial</h3>
<p>No exemplo da <em>granulometria</em>, <span class="math inline">\(i=1,2,3\)</span> e a equação <a href="ade.html#eq:mod1fator2">(4.2)</a> pode ser escrita como</p>
<p><span class="math display">\[\begin{align*}
Y_{1j}&amp;=\mu+\tau_1+\varepsilon_{1j}\\
Y_{2j}&amp;=\mu+\tau_2+\varepsilon_{2j}\\
Y_{3j}&amp;=\mu+\tau_3+\varepsilon_{3j}\\
\end{align*}\]</span></p>
<p>em que <span class="math inline">\(j = 1,\dots,4,\)</span> nesse caso. Podemos escrever esse mesmo modelo de forma concisa usando a notação matricial como:</p>
<p><span class="math display" id="eq:mod1fatmatriz">\[\begin{equation}
{\bf y}={\bf X }\boldsymbol{\beta}+\boldsymbol{\varepsilon},
\tag{4.6}
\end{equation}\]</span>
em que</p>
<p><span class="math display">\[{\bf y}=\left(\begin{array}{l}
y_{11} \\
y_{12} \\
y_{13} \\
y_{14} \\
y_{21} \\
y_{22} \\
y_{23} \\
y_{24} \\
y_{31} \\
y_{32} \\
y_{33} \\
y_{34}
\end{array}\right),\quad  {\bf X}=\left(\begin{array}{cccc}
1 &amp; 1 &amp; 0 &amp; 0 \\
1 &amp; 1 &amp; 0 &amp; 0 \\
1 &amp; 1 &amp; 0 &amp; 0 \\
1 &amp; 1 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 1 &amp; 0 \\
1 &amp; 0 &amp; 1 &amp; 0 \\
1 &amp; 0 &amp; 1 &amp; 0 \\
1 &amp; 0 &amp; 1 &amp; 0 \\
1 &amp; 0 &amp; 0 &amp; 1 \\
1 &amp; 0 &amp; 0 &amp; 1 \\
1 &amp; 0 &amp; 0 &amp; 1 \\
1 &amp; 0 &amp; 0 &amp; 1
\end{array}\right), \quad\boldsymbol{\beta}=\left(\begin{array}{l}
\mu \\
\tau_{1} \\
\tau_{2} \\
\tau_{3}
\end{array}\right), \quad\boldsymbol{\varepsilon}=\left(\begin{array}{c}
\epsilon_{11} \\
\epsilon_{12} \\
\epsilon_{13} \\
\epsilon_{14} \\
\epsilon_{21} \\
\epsilon_{22} \\
\epsilon_{23} \\
\epsilon_{24} \\
\epsilon_{31} \\
\epsilon_{32} \\
\epsilon_{33} \\
\epsilon_{34}
\end{array}\right)
\]</span>
em que <span class="math inline">\(\boldsymbol{\varepsilon} \sim MVN({\bf 0}, \sigma^2{\bf I}).\)</span></p>
<p>O problema de minimizar a equação <a href="ade.html#eq:sqe">(4.5)</a> é equivalente à resolver a equação <span class="math inline">\({\bf X&#39;X}\boldsymbol{\beta}={\bf X&#39;y}\)</span> no contexto matricial. Nesse caso é necessário que <span class="math inline">\({\bf X&#39;X}\)</span> seja invertível e para que isso aconteça é necessário que as colunas de <span class="math inline">\({\bf X }\)</span> sejam linearmente independentes. Ao usarmos <span class="math inline">\({\bf X }\)</span> com 4 colunas como definida acima, termos que a coluna 1 é combinação linear das outras 3, e isso implicará na não invertibilidade de <span class="math inline">\({\bf X&#39;X}\)</span>. Por isso é necessário reescrever <span class="math inline">\({\bf X }\)</span> com apenas 3 colunas, removendo aquela correspondente ao primeiro nível do fator (tempo igual à 5 segundos). Dessa forma,</p>
<p><span class="math display">\[{\bf X}=\left(\begin{array}{lll}
1 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 0 \\
1 &amp; 0 &amp; 0 \\
1 &amp; 1 &amp; 0 \\
1 &amp; 1 &amp; 0 \\
1 &amp; 1 &amp; 0 \\
1 &amp; 1 &amp; 0 \\
1 &amp; 0 &amp; 1 \\
1 &amp; 0 &amp; 1 \\
1 &amp; 0 &amp; 1 \\
1 &amp; 0 &amp; 1
\end{array}\right)
\]</span></p>
<p>Esta codificação de tratamento torna <em>padrão</em> o primeiro nível do fator, e
todos os outros níveis do fator são comparados a ele. Para o exemplo com <span class="math inline">\(K = 3\)</span>
níveis de fator, a solução para via método de mínimos quadrados (MQO) de <span class="math inline">\({\bf X&#39;X\beta=X&#39;y}\)</span> é</p>
<p><span class="math display" id="eq:mqomatric">\[\begin{equation}
\hat{\boldsymbol{\beta}}=\left(\boldsymbol{X}^{\prime} \boldsymbol{X}\right)^{-1} \boldsymbol{X}^{\prime} \boldsymbol{y},
\tag{4.7}
\end{equation}\]</span></p>
<p>o que resulta em
<span class="math display">\[
\hat{\boldsymbol{\beta}}=\left(\begin{array}{c}
\hat{\mu}+\hat{\tau}_{1} \\
\hat{\tau}_{2}-\hat{\tau}_{1} \\
\hat{\tau}_{3}-\hat{\tau}_{1}
\end{array}\right),
\]</span>
ou seja, nessa fomulação é retornado a diferença do tratamento 2 para o tratamento 1 (<span class="math inline">\(\hat{\tau}_{2}-\hat{\tau}_{1}\)</span>) e a diferença do tratamento 3 para o tratamento 1 (<span class="math inline">\(\hat{\tau}_{3}-\hat{\tau}_{1}\)</span>). Em termos de testes de hipóteses, para que exista diferença entre os tratamentos, basta que <span class="math inline">\(\hat{\tau}_{2}-\hat{\tau}_{1}\)</span> ou <span class="math inline">\(\hat{\tau}_{3}-\hat{\tau}_{1}\)</span> seja significativamente diferente de zero.</p>
</div>
<div id="mínimos-quadrados-matricial-com-o-r" class="section level3">
<h3><span class="header-section-number">4.2.7</span> Mínimos quadrados matricial com o <code>R</code></h3>
<p>Vamos usar o <code>R</code> para resolver essas diferentes equações através de MQO e entender os resultados.</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" title="1">y=dados.g<span class="op">$</span>Ganho.de.Peso           <span class="co"># variável resposta/dependente</span></a>
<a class="sourceLine" id="cb381-2" title="2">z10=<span class="kw">rep</span>(<span class="dv">0</span>,n)</a>
<a class="sourceLine" id="cb381-3" title="3">z10[<span class="kw">which</span>(dados.g<span class="op">$</span>fator<span class="op">==</span><span class="st">&quot;T10&quot;</span>)]=<span class="dv">1</span></a>
<a class="sourceLine" id="cb381-4" title="4">z15=<span class="kw">rep</span>(<span class="dv">0</span>,n)</a>
<a class="sourceLine" id="cb381-5" title="5">z15[<span class="kw">which</span>(dados.g<span class="op">$</span>fator<span class="op">==</span><span class="st">&quot;T15&quot;</span>)]=<span class="dv">1</span></a>
<a class="sourceLine" id="cb381-6" title="6">X=<span class="kw">matrix</span>(<span class="kw">c</span>(<span class="kw">rep</span>(<span class="dv">1</span>,n),z10,z15),<span class="dt">nrow=</span>n,<span class="dt">ncol=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb381-7" title="7"><span class="co">#X=model.matrix(~dados.g$fator)    # criando a matrix X do modelo matricial</span></a>
<a class="sourceLine" id="cb381-8" title="8"><span class="kw">colnames</span>(X)=<span class="kw">c</span>(<span class="st">&quot;Intercepto&quot;</span>,<span class="st">&quot;Fator.10&quot;</span>,<span class="st">&quot;Fator.15&quot;</span>)</a>
<a class="sourceLine" id="cb381-9" title="9">X</a></code></pre></div>
<pre><code>##       Intercepto Fator.10 Fator.15
##  [1,]          1        0        1
##  [2,]          1        1        0
##  [3,]          1        0        1
##  [4,]          1        0        0
##  [5,]          1        1        0
##  [6,]          1        1        0
##  [7,]          1        0        0
##  [8,]          1        0        1
##  [9,]          1        0        1
## [10,]          1        0        0
## [11,]          1        1        0
## [12,]          1        0        0</code></pre>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb383-1" title="1">beta=<span class="st"> </span><span class="kw">solve</span>(<span class="kw">t</span>(X)<span class="op">%*%</span>X)<span class="op">%*%</span><span class="kw">t</span>(X)<span class="op">%*%</span>y  <span class="co"># MQO matricial </span></a>
<a class="sourceLine" id="cb383-2" title="2"><span class="kw">print</span>(beta)</a></code></pre></div>
<pre><code>##                  [,1]
## Intercepto 40.1726305
## Fator.10    0.6942883
## Fator.15    2.6834468</code></pre>
<p>Assim temos que a diferença nas médias de ganho de peso para os animais que foram tratados com granulagem “10” para os que foram tratados com granulagem “5” é <span class="math inline">\(\hat{\tau}_{2}-\hat{\tau}_{1} = 0.6942883\)</span> e a diferença nas médias de ganho de peso para os animais que foram tratados com granulagem “15” para os que foram tratados com granulagem “5” é <span class="math inline">\(\hat{\tau}_{3}-\hat{\tau}_{1}=2.6834468\)</span>.</p>
</div>
<div id="função-lm" class="section level3">
<h3><span class="header-section-number">4.2.8</span> Função <code>lm()</code></h3>
<p>Podemos obter o mesmo resultado usando a função <code>lm()</code> do <code>R</code>. Aqui vamos usar um recurso do <code>R</code> que permite “anexar” um conjunto de dados ou objeto do tipo list ou <em>data.frame</em> utilizando a função <code>attach()</code>. Ao anexar esse objeto os componentes se tornem imediatamente disponíveis e portanto podemos, por exemplo, digitar somente <em>fator</em> ao invés de <em>dados.g$fator</em>.</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb385-1" title="1"><span class="kw">attach</span>(dados.g)            <span class="co"># anexando os dados</span></a>
<a class="sourceLine" id="cb385-2" title="2"><span class="co"># relevel(fator, ref = &quot;T5&quot;) fixa o nível T5 da variável fator como referência</span></a>
<a class="sourceLine" id="cb385-3" title="3">modelo1=<span class="kw">lm</span>(Ganho.de.Peso <span class="op">~</span><span class="st"> </span><span class="kw">relevel</span>(fator, <span class="dt">ref =</span> <span class="st">&quot;T5&quot;</span>))</a>
<a class="sourceLine" id="cb385-4" title="4">coeficientes=<span class="kw">coef</span>(modelo1)</a>
<a class="sourceLine" id="cb385-5" title="5"><span class="kw">names</span>(coeficientes)=<span class="kw">c</span>(<span class="st">&quot;Intercepto&quot;</span>,<span class="st">&quot;Fator.10&quot;</span>,<span class="st">&quot;Fator.15&quot;</span>)</a>
<a class="sourceLine" id="cb385-6" title="6">coeficientes</a></code></pre></div>
<pre><code>## Intercepto   Fator.10   Fator.15 
## 40.1726305  0.6942883  2.6834468</code></pre>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb387-1" title="1"><span class="kw">detach</span>(dados.g)      <span class="co">#&quot;des&quot;anexando os dados</span></a></code></pre></div>
<p>Observe que o resultado é exatamente o mesmo, quando usamos o modelo matricial.</p>
</div>
<div id="estimação-da-variância-sigma2" class="section level3">
<h3><span class="header-section-number">4.2.9</span> Estimação da variância <span class="math inline">\(\sigma^2\)</span></h3>
<p>A estimativa da variância do erro experimental, <span class="math inline">\(\sigma^2\)</span>, é</p>
<p><span class="math display" id="eq:varsse1">\[\begin{equation}
\widehat{\sigma^2}=\frac{SQE}{n-k}.
\tag{4.8}
\end{equation}\]</span></p>
<p>Assim, só é possível estimar essa variância quando há replicações em cada nível do fator de tratamento (<span class="math inline">\(n-k&gt;0\)</span>). Quando as medições em sub-amostras ou medidas repetidas da mesma unidade experimental são tratadas como replicações, esta estimativa pode ser seriamente enviesada. Na forma matricial podemos calcular o <span class="math inline">\(SQE\)</span> da seguinte forma</p>
<p><span class="math display" id="eq:sqem">\[\begin{equation}
SQE=\boldsymbol{y}^{\prime} \boldsymbol{y}-\hat{\boldsymbol{\beta}}^{\prime} \boldsymbol{X}^{\prime} \boldsymbol{y}=\boldsymbol{y}^{\prime}\left(\boldsymbol{I}-\boldsymbol{X}\left(\boldsymbol{X}^{\prime} \boldsymbol{X}\right)^{-1} \boldsymbol{X}^{\prime}\right) \boldsymbol{y}
\tag{4.9}
\end{equation}\]</span></p>
<p>e pode-se demonstrar que a razão da soma do quadrado dos erros pela variância do erro experimental, <span class="math inline">\(SQE/\sigma^2\)</span>, segue uma distribuição qui-quadrado com <span class="math inline">\(n-k\)</span> graus de liberdade, ou seja,</p>
<p><span class="math display" id="eq:distsqe">\[\begin{equation}
\frac{SQE}{ \sigma^{2}} \sim \chi_{n-k}^{2}.
\tag{4.10}
\end{equation}\]</span></p>
<p>Para o exemplo da granulometria podemos obter, <span class="math inline">\(SQE\)</span> de duas formas. Calculando diretamente usando a formulação matricial</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb388-1" title="1">I=<span class="kw">diag</span>(<span class="kw">length</span>(y)) <span class="co">#Matriz diagonal 12x12</span></a>
<a class="sourceLine" id="cb388-2" title="2">SQE=<span class="st"> </span><span class="kw">t</span>(y)<span class="op">%*%</span>(I<span class="op">-</span>X<span class="op">%*%</span><span class="kw">solve</span>(<span class="kw">t</span>(X)<span class="op">%*%</span>X)<span class="op">%*%</span><span class="kw">t</span>(X))<span class="op">%*%</span>y  <span class="co"># SQE matricial </span></a>
<a class="sourceLine" id="cb388-3" title="3"><span class="kw">print</span>(SQE)</a></code></pre></div>
<pre><code>##          [,1]
## [1,] 11.59738</code></pre>
<p>ou, a partir do modelo ajustado através da função <code>lm()</code> e gaurdado na variável <em>modelo1</em></p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb390-1" title="1">SSE=<span class="kw">sum</span>(modelo1<span class="op">$</span>residuals<span class="op">**</span><span class="dv">2</span>) </a>
<a class="sourceLine" id="cb390-2" title="2"><span class="kw">print</span>(SSE)</a></code></pre></div>
<pre><code>## [1] 11.59738</code></pre>
</div>
<div id="teste-de-hipótese-para-efeito-dos-tratamentos" class="section level3">
<h3><span class="header-section-number">4.2.10</span> Teste de hipótese para efeito dos tratamentos</h3>
<p>No modelo com DCC como representado na equação <a href="ade.html#eq:mod1fator">(4.1)</a> as hipóteses estatísticas de interesse são <span class="math inline">\(H_0: \mu_1=\mu_2=\dots=\mu_k\)</span> versus a hipótese altenrativa <span class="math inline">\(H_1\)</span> de que pelo menos uma das médias é diferente das demais. No modelo com DCC como representado na equação <a href="ade.html#eq:mod1fator2">(4.2)</a>, as hipóteses estatísticas de interesse são <span class="math inline">\(H_0: \tau_1=\tau_2=\dots=\tau_k\)</span> versus a hipótese altenrativa <span class="math inline">\(H_1\)</span> de que pelo menos um dos <span class="math inline">\(\tau&#39;s\)</span> é diferente dos demais. Se a hipótese nula for verdadeira, o modelo <span class="math inline">\(y_{ij} = \mu_i +\varepsilon_{ij} = \mu+ \tau_i+\varepsilon_{ij}\)</span> simplifica
para <span class="math inline">\(y_{ij} = \mu + \varepsilon_{ij}\)</span>, que pode ser representado como uma única distribuição normal com média <span class="math inline">\(\mu\)</span> e variância <span class="math inline">\(\sigma^2\)</span> em vez de distribuições normais múltiplas como aquelas
mostrado na Figura <a href="ade.html#fig:figmus">4.2</a>.</p>
<p>Cada observação <span class="math inline">\(y_{ij}\)</span> da variável resposta <span class="math inline">\(y\)</span> se afasta da média geral <span class="math inline">\(\overline{y}_{..}\)</span> por um valor <span class="math inline">\(y_{ij}-\overline{y}_{..}\)</span>. A soma dos quadrados desses valores (soma dos quadrados totais, <span class="math inline">\(SQT\)</span>) é dado por</p>
<p><span class="math display" id="eq:sqt">\[\begin{equation}
SQT=\sum_{i=1}^{k} \sum_{j=1}^{r_{i}}\left(y_{i j}-\bar{y}_{..}\right)^{2}=\boldsymbol{y}^{\prime} \boldsymbol{y}-\left(\boldsymbol{1}^{\prime} \boldsymbol{y}\right)^{2} /\left(\boldsymbol{1}^{\prime} \boldsymbol{1}\right)
\tag{4.11}
\end{equation}\]</span>
em que <span class="math inline">\(\boldsymbol{1}\)</span> é um vetor coluna <span class="math inline">\(n\)</span>-dimensional de uns. Além disso temos a relação</p>
<p><span class="math display" id="eq:sqtsqsqe">\[\begin{equation}
SQT=SQ+SQE
\tag{4.12}
\end{equation}\]</span>
em que <span class="math inline">\(SQ\)</span> é a parcela que corresponde ao tratamento. Matricialmente, <span class="math inline">\(SQ\)</span> pode ser escrito como</p>
<p><span class="math display" id="eq:sq">\[\begin{equation}
SQ=\hat{\boldsymbol{\beta}}^{\prime} \boldsymbol{X}^{\prime} \boldsymbol{y}-\left(\mathbf{1}^{\prime} \boldsymbol{y}\right)^{2} /\left(\mathbf{1}^{\prime} \mathbf{1}\right)
\tag{4.13}
\end{equation}\]</span></p>
</div>
<div id="análise-de-variância---anova" class="section level3">
<h3><span class="header-section-number">4.2.11</span> Análise de variância - ANOVA</h3>
<p>Sob a hipótese nula <span class="math inline">\(H_0: \mu_1=\mu_2=\dots=\mu_k\)</span>, ambos <span class="math inline">\(SQT\)</span> e <span class="math inline">\(SQE\)</span> seguem a distribuição qui-quadrado. Essas somas de quadrados e seus quadrados médios correspondentes, que são formados pela divisão cada soma de quadrados por seus graus de liberdade, geralmente são apresentados em um
<strong>análise de variância</strong> ou tabela <strong>ANOVA</strong> como aquela mostrada simbolicamente na Tabela <a href="ade.html#tab:ta">4.1</a>.</p>
<p><br><br></p>
<table>
<caption><span id="tab:ta">Tabela 4.1: </span> ANOVA</caption>
<thead>
<tr class="header">
<th>Fonte</th>
<th align="center">gl</th>
<th align="center">Soma dos quadrados</th>
<th align="center">Media dos quadrados</th>
<th align="center">Estatística F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tratamento</td>
<td align="center">k-1</td>
<td align="center">SQ</td>
<td align="center">mSQ = SQ/(k-1)</td>
<td align="center">F=mSQT/mSQE</td>
</tr>
<tr class="even">
<td>Erro</td>
<td align="center">n-k</td>
<td align="center">SQE</td>
<td align="center">mSQE = SQE/(n-k)</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="center">n-1</td>
<td align="center">SQT</td>
<td align="center">mSQT = SQT/(n-1)</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p><br><br></p>
<p>Sob a hipótese nula, a estatística <span class="math inline">\(F=mSQT/mSQE\)</span> segue a distribuição <span class="math inline">\(F\)</span>
com <span class="math inline">\(k-1\)</span> e <span class="math inline">\(n-k\)</span> graus de liberdade.</p>
<p>Podemos obter a Tabela ANOVA <a href="ade.html#tab:ta">4.1</a> para o exemplo <a href="ade.html#granu">4.2.1</a> da granulometria utilizando a função <code>aov()</code> do <code>R</code>. As entradas para a função <code>aov()</code> são as mesmas da função <code>lm()</code> mostrado anteriormente, mas o resumo de um objeto criado pela função <code>aov()</code> é a tabela ANOVA em vez das estimativas produzidas pela função <code>lm()</code>. Para o exemplo <a href="ade.html#granu">4.2.1</a> a tabela ANOVA pode ser obtida fazendo-se</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb392-1" title="1">anova.tab&lt;-<span class="st"> </span><span class="kw">aov</span>(Ganho.de.Peso <span class="op">~</span><span class="st"> </span>fator, <span class="dt">data =</span> dados.g )</a>
<a class="sourceLine" id="cb392-2" title="2"><span class="kw">summary</span>(anova.tab)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## fator        2  15.52   7.760   6.022 0.0219 *
## Residuals    9  11.60   1.289                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Além da tabela ANOVA completa, a função <code>aov()</code> retorna também o p-valor do teste para igualdade de médias que tem a seguinte configuração das hipóteses</p>
<p><span class="math display">\[\begin{align} 
H_0&amp;: \mu_1=\mu_2=\dots=\mu_k, \\
H_1&amp;: \mu_r\neq \mu_s, \mbox{ para algum } r\neq s.
\end{align}\]</span></p>
<p>O p-valor do teste <span class="math inline">\(F\)</span> pode ser obtido por</p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb394-1" title="1"><span class="kw">summary</span>(anova.tab)[[<span class="dv">1</span>]][[<span class="dv">1</span>,<span class="st">&quot;Pr(&gt;F)&quot;</span>]]</a></code></pre></div>
<pre><code>## [1] 0.02187943</code></pre>
<pre><code>## Warning: Ignoring unknown parameters: output</code></pre>
<pre><code>## Warning in is.na(x): is.na() aplicado a um objeto diferente de lista ou vetor de
## tipo &#39;expression&#39;</code></pre>
<div class="figure"><span id="fig:pvalorf"></span>
<img src="R-aplicado-a-suinocultura_files/figure-html/pvalorf-1.png" alt="p-valor do teste F" width="672" />
<p class="caption">
Figura 4.3: p-valor do teste F
</p>
</div>
<p>Para o exemplo <a href="ade.html#granu">4.2.1</a> temos que p-valor=0.0219, assim, adotando-se <span class="math inline">\(\alpha=0.05\)</span> como nível de significância chegamos a conclusão que pelo menos uma das médias é signioficativamente diferente das demais.</p>
</div>
<div id="verificação-das-suposições-do-modelo-linear" class="section level3">
<h3><span class="header-section-number">4.2.12</span> Verificação das suposições do modelo linear</h3>
</div>
<div id="fatores-e-delineamentos-fatoriais" class="section level3">
<h3><span class="header-section-number">4.2.13</span> Fatores e delineamentos fatoriais</h3>
<ul>
<li>Muitos experimentos envolvem o estudo de efeitos de dois ou mais <strong>fatores</strong>.</li>
<li>Em geral, <strong>delineamentos fatoriais</strong> são mais eficientes para este tipo de experimento.</li>
<li>Por delineamento fatorial, queremos dizer que em cada replicação completa do experimento todas as possíveis combinações são investigadas.
<ul>
<li>Por exemplo, se existem <span class="math inline">\(a\)</span> níveis do fator <span class="math inline">\(A\)</span> e <span class="math inline">\(b\)</span> níveis do fator <span class="math inline">\(B\)</span>, cada replicação contém todas as combinações de tratamentos <span class="math inline">\(ab\)</span>.</li>
</ul></li>
<li>Quando os fatores são organizados em um delineamento fatorial, eles costumam ser <strong>cruzados</strong>.</li>
</ul>
</div>
<div id="fatores-e-delineamentos-fatoriais-1" class="section level3">
<h3><span class="header-section-number">4.2.14</span> Fatores e delineamentos fatoriais</h3>
<ul>
<li>De maneira geral, quando se fala de fatoriais não se está falando em delineamentos de experimentos, e sim em <strong>delineamentos de tratamentos</strong>.
<ul>
<li>No entanto, como será visto no curso, existem algumas modificações nos delineamentos básicos que só podem ser aplicadas aos ensaios fatoriais.</li>
</ul></li>
</ul>
</div>
<div id="fatores-e-delineamentos-fatoriais-2" class="section level3">
<h3><span class="header-section-number">4.2.15</span> Fatores e delineamentos fatoriais</h3>
<ul>
<li>Chama-se de fator àquilo que se quer testar e de níveis às suas diferentes manifestações.
<ul>
<li>Por exemplo, em estudos de adubação de plantas, três elementos - nitrogênio (N), fósforo (P) e potássio (K) - são considerados os macronutrientes.
<ul>
<li>Assim, cada elemento é considerado um fator, e suas diferentes doses de aplicação níveis.</li>
<li>Se apenas um elemento for testado num ensaio, cada nível será chamado de tratamento.</li>
<li>Por sua vez, se dois ou três elementos forem testados, cada combinação entre seus níveis é que será declarada como um tratamento.</li>
</ul></li>
</ul></li>
<li>Os fatores podem ser <strong>quantitativos</strong>: doses, espaçamento entre plantas, etc; ou <strong>qualitativos</strong>: cultivares, etc.</li>
</ul>
</div>
<div id="efeitos-principais" class="section level3">
<h3><span class="header-section-number">4.2.16</span> Efeitos principais</h3>
<ul>
<li>O efeito de um fator é definido como a mudança na resposta produzida pela mudança no nível do fator.
<ul>
<li>Este é frequentemente chamado de <strong>efeito principal</strong> porque se refere aos principais fatores no experimento.</li>
</ul></li>
</ul>
<div id="experimento-fatorial-com-dois-fatores-com-dois-níveis" class="section level4">
<h4><span class="header-section-number">4.2.16.1</span> Experimento fatorial com dois fatores com dois níveis</h4>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb398-1" title="1"> <span class="kw">set.seed</span>(<span class="dv">7638</span>)</a>
<a class="sourceLine" id="cb398-2" title="2"> f &lt;-<span class="st"> </span><span class="kw">factor</span>( <span class="kw">rep</span>( <span class="kw">c</span>(<span class="dv">35</span>, <span class="dv">40</span>, <span class="dv">45</span> ), <span class="dt">each =</span> <span class="dv">4</span>))</a>
<a class="sourceLine" id="cb398-3" title="3"> fac &lt;-<span class="st"> </span><span class="kw">sample</span>( f, <span class="dv">12</span> )</a>
<a class="sourceLine" id="cb398-4" title="4"> eu &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">12</span></a>
<a class="sourceLine" id="cb398-5" title="5"> plan &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">loaf=</span>eu, <span class="dt">time=</span>fac )</a></code></pre></div>
<!-- ![fig5.1](images/fig5_1.png) -->
</div>
</div>
<div id="efeitos-principais-1" class="section level3">
<h3><span class="header-section-number">4.2.17</span> Efeitos principais</h3>
<p><span class="math display">\[
A = \bar{y}_{A^{+}} - \bar{y}_{A^{-}} = \frac{40 + 52}{2} - \frac{20 + 30}{2} = 21
\]</span></p>
<ul>
<li><strong>Aumento na média da resposta</strong> de 21 unidades.</li>
<li>Similarmente, temos que o efeito principal de <span class="math inline">\(B\)</span> é</li>
</ul>
<p><span class="math display">\[
B = \bar{y}_{B^{+}} - \bar{y}_{B^{-}} = \frac{30 + 52}{2} - \frac{20 + 40}{2} = 11
\]</span></p>
</div>
<div id="efeito-de-interação" class="section level3">
<h3><span class="header-section-number">4.2.18</span> Efeito de interação</h3>
<ul>
<li>Em alguns experimentos, nós poderemos encontrar que a diferença na resposta entre os níveis de um fator não é o mesmo em todos os níveis dos outros fatores.</li>
<li>Quando isto ocorre, existe uma <strong>interação</strong> entre os fatores.</li>
</ul>
<div id="outro-experimento-fatorial-com-dois-fatores-com-dois-níveis" class="section level4">
<h4><span class="header-section-number">4.2.18.1</span> Outro experimento fatorial com dois fatores com dois níveis</h4>
<!-- ![Fig5.2](images/Fig5_2.png) -->
</div>
</div>
<div id="efeito-de-interação-1" class="section level3">
<h3><span class="header-section-number">4.2.19</span> Efeito de interação</h3>
<ul>
<li>No nível <span class="math inline">\(B^{-}\)</span>, o efeito de <span class="math inline">\(A\)</span> é</li>
</ul>
<p><span class="math display">\[
A = 50 - 20 = 30
\]</span></p>
<ul>
<li>No nível <span class="math inline">\(B^{+}\)</span>, o efeito de <span class="math inline">\(A\)</span> é</li>
</ul>
<p><span class="math display">\[
A = 12 - 40 = - 28
\]</span></p>
<ul>
<li>A magnitude do efeito de interação é a diferença média desses dois efeitos <span class="math inline">\(A\)</span>, ou</li>
</ul>
<p><span class="math display">\[
AB = \frac{-28 - 30}{2} = -29
\]</span></p>
</div>
<div id="efeito-de-interação-2" class="section level3">
<h3><span class="header-section-number">4.2.20</span> Efeito de interação</h3>
<!-- <div id="left"> -->
<!-- ![Fig5.3](images/Fig5_3.png) -->
<!-- </div> -->
<!-- <div id="right"> -->
<!-- ![Fig5.4](images/Fig5_4.png) -->
<!-- </div> -->
</div>
<div id="representação-por-modelo-de-regressão" class="section level3">
<h3><span class="header-section-number">4.2.21</span> Representação por modelo de regressão</h3>
<p><span class="math display">\[
y = \beta_0 + \beta_1x_1 + \beta_2x_2 + \beta_{12}x_1x_2 + \epsilon
\]</span></p>
<ul>
<li><span class="math inline">\(y\)</span> é a resposta</li>
<li><span class="math inline">\(\beta\)</span>’s são parâmetros</li>
<li><span class="math inline">\(x_1\)</span> representa o fator <span class="math inline">\(A\)</span> (escala contínua de -1 a 1)</li>
<li><span class="math inline">\(x_2\)</span> representa o fator <span class="math inline">\(B\)</span> (escala contínua de -1 a 1)</li>
<li><span class="math inline">\(\epsilon\)</span> é o erro aleatório</li>
</ul>
</div>
<div id="representação-por-modelo-de-regressão-ausência-de-interação" class="section level3">
<h3><span class="header-section-number">4.2.22</span> Representação por modelo de regressão (ausência de interação)</h3>
<p><span class="math display">\[
\hat{y} = 35.5 + 10.5x_1 + 5.5x_2 + 0.5x_1x_2 \approx 35.5 + 10.5x_1 + 5.5x_2
\]</span></p>
<!-- <div id="left"> -->
<p><img src="R-aplicado-a-suinocultura_files/figure-html/Fig5_5-1.png" width="672" />
<!-- </div> --></p>
<!-- <div id="right"> -->
<p><img src="R-aplicado-a-suinocultura_files/figure-html/Fig5_5b-1.png" width="672" />
<!-- </div> --></p>
</div>
<div id="representação-por-modelo-de-regressão-presença-de-interação" class="section level3">
<h3><span class="header-section-number">4.2.23</span> Representação por modelo de regressão (presença de interação)</h3>
<p><span class="math display">\[
\hat{y} = 35.5 + 10.5x_1 + 5.5x_2 + 8x_1x_2
\]</span></p>
<!-- <div id="left"> -->
<p><img src="R-aplicado-a-suinocultura_files/figure-html/Fig5_6-1.png" width="672" />
<!-- </div> --></p>
<!-- <div id="right"> -->
<p><img src="R-aplicado-a-suinocultura_files/figure-html/Fig5_6b-1.png" width="672" />
<!-- </div> --></p>
<p><strong>“Interação é uma forma de curvatura”</strong></p>
</div>
<div id="efeitos-principais-vs-efeito-de-interação" class="section level3">
<h3><span class="header-section-number">4.2.24</span> Efeitos principais <em>vs</em> efeito de interação</h3>
<ul>
<li>Geralmente quando um efeito de interação é grande, os efeitos principais correspondentes têm pouco significado prático.</li>
</ul>
<!-- <div id="left"> -->
<!-- ![Fig5.2](images/Fig5_2.png) -->
<!-- </div> -->
<!-- <div id="right"> -->
<ul>
<li><span class="math inline">\(A = \bar{y}_{A^{+}} - \bar{y}_{A^{-}} = \frac{50 + 12}{2} - \frac{20 + 40}{2} = 1\)</span>, que é bem pequeno, e nós ficamos tentados a concluir que não existe efeito devido ao <span class="math inline">\(A\)</span>.</li>
<li>No entanto, quando examinamos os efeitos de <span class="math inline">\(A\)</span> em <em>diferentes níveis do fator <span class="math inline">\(B\)</span></em>, vemos que isto não se confirma.
<ul>
<li>O fator <span class="math inline">\(A\)</span> tem um efeito, mas <em>depende do nível do fator <span class="math inline">\(B\)</span></em>.</li>
</ul></li>
</ul>
<!-- </div> -->
</div>
<div id="efeitos-principais-vs-efeito-de-interação-1" class="section level3">
<h3><span class="header-section-number">4.2.25</span> Efeitos principais <em>vs</em> efeito de interação</h3>
<ul>
<li>Ou seja, o conhecimento da interação <span class="math inline">\(AB\)</span> é mais útil que o conhecimento do efeito principal.</li>
<li>Uma interação significativa geralmente irá <strong>mascarar</strong> a significância dos efeitos principais.</li>
<li>Na presença de interação significativa, o pesquisador deve usualmente examinar os níveis de um fator, fator <span class="math inline">\(A\)</span>, com os níveis do outro fator fixados para obter conclusões sobre efeito principal de <span class="math inline">\(A\)</span>.</li>
</ul>
</div>
</div>
<div id="delineamento-fatorial-com-dois-fatores" class="section level2">
<h2><span class="header-section-number">4.3</span> Delineamento fatorial com dois fatores</h2>
<div id="delineamento-fatorial-com-dois-fatores-1" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Delineamento fatorial com dois fatores</h3>
<ul>
<li>Os tipos de delineamentos fatoriais mais simples envolvem apenas dois fatores ou conjuntos de tratamentos.</li>
<li>Existem <span class="math inline">\(a\)</span> níveis do fator <span class="math inline">\(A\)</span> e <span class="math inline">\(b\)</span> níveis do fator <span class="math inline">\(B\)</span>, e estes são organizados em um delineamento fatorial.</li>
</ul>
</div>
</div>
<div id="exemplo-da-bateria" class="section level2">
<h2><span class="header-section-number">4.4</span> Exemplo da bateria</h2>
<!-- ![FigBateria](images/bateria.jpg) -->
<ul>
<li>Um engenheiro está desenhando uma bateria para ser usada em um dispositivo que estará sujeita a variações de temperatura.
<ul>
<li>Três tipos de materiais (MT) são possíveis para a fabricação da bateria.</li>
<li>Três temperaturas, consistentes com as temperaturas do ambiente de uso.</li>
<li>Quatro baterias foram testadas em cada combinação de material e temperatura.</li>
</ul></li>
<li><strong>Delineamento fatorial <span class="math inline">\(3^2\)</span></strong>.</li>
</ul>
<div id="exemplo-da-bateria-1" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Exemplo da bateria</h3>
<!-- ![Tab5_1](images/Tab5_1.png) -->
<blockquote>
<ol style="list-style-type: decimal">
<li>Quais os efeitos do tipo e temperatura do material na vida?</li>
<li>Existe uma escolha de material que daria vida longa, independentemente da temperatura (um <strong>produto robusto</strong>)?
## Exemplo da bateria</li>
</ol>
</blockquote>
<!-- ![Tab5_2](images/Tab5_2.png) -->
<ul>
<li><span class="math inline">\(a\)</span> níveis do fator <span class="math inline">\(A\)</span>; <span class="math inline">\(b\)</span> níveis do fator <span class="math inline">\(B\)</span>; <span class="math inline">\(n\)</span> replicações.</li>
<li>Este é um <strong>delineamento completamente aleatorizado</strong>.</li>
</ul>
</div>
<div id="exemplo-da-bateria-2" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Exemplo da bateria</h3>
<!-- ![Tab5_2](images/Tab5_2.png) -->
<ul>
<li>O <strong>modelo de efeitos</strong>:</li>
</ul>
<p><span class="math display">\[
y_{ijk} = \mu + \tau_i + \beta_j + (\tau\beta)_{ij} + \epsilon_{ijk}, i = 1, \ldots, a, j = 1,\ldots, b, k = 1, \ldots, n.
\]</span></p>
</div>
<div id="exemplo-da-bateria-3" class="section level3">
<h3><span class="header-section-number">4.4.3</span> Exemplo da bateria</h3>
<ul>
<li>Em um experimento fatorial com dois fatores, os fatores <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> são de igual interesse.</li>
<li>Especificamente, estamos interessados em <strong>testar hipóteses</strong> sobre a igualdade dos efeitos de tratamento das linhas</li>
</ul>
<p><span class="math display">\[
H_0: \tau_1 = \tau_2 = \ldots = \tau_a = 0\quad vs.\quad H_1:\mbox{pelo menos um } \tau_i \neq 0
\]</span>
e a igualdade dos efeitos de tratamento das colunas</p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_2 = \ldots = \beta_b = 0\quad vs.\quad H_1:\mbox{pelo menos um } \beta_j \neq 0
\]</span></p>
<ul>
<li>Também estamos interessados em determinar em que linha e coluna os tratamentos <em>interagem</em></li>
</ul>
<p><span class="math display">\[
H_0: (\tau\beta)_{ij} = 0\quad vs.\quad H_1:\mbox{pelo menos um } (\tau\beta)_{ij} \neq 0
\]</span>
- <strong>Pergunta:</strong> O que estas hipóteses representam na prática?
- <em>Cenas dos próximos capítulos:</em> <strong>Análise de variância de dois fatores</strong></p>
</div>
</div>
<div id="criando-um-planejamento-fatorial-com-dois-fatores-no-r" class="section level2">
<h2><span class="header-section-number">4.5</span> Criando um planejamento fatorial com dois fatores no <code>R</code></h2>
<div id="exemplo-da-bateria-4" class="section level3">
<h3><span class="header-section-number">4.5.1</span> Exemplo da bateria</h3>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb399-1" title="1">D &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(<span class="dt">MT =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dt">T =</span> <span class="kw">c</span>(<span class="dv">15</span>, <span class="dv">70</span>, <span class="dv">125</span>))</a>
<a class="sourceLine" id="cb399-2" title="2">D</a></code></pre></div>
<pre><code>##   MT   T
## 1  1  15
## 2  2  15
## 3  3  15
## 4  1  70
## 5  2  70
## 6  3  70
## 7  1 125
## 8  2 125
## 9  3 125</code></pre>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb401-1" title="1">D &lt;-<span class="st"> </span><span class="kw">rbind</span>(D, D, D, D)</a>
<a class="sourceLine" id="cb401-2" title="2"><span class="kw">set.seed</span>(<span class="dv">2591</span>)</a>
<a class="sourceLine" id="cb401-3" title="3">D &lt;-<span class="st"> </span>D[<span class="kw">order</span>(<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">36</span>)), ]</a>
<a class="sourceLine" id="cb401-4" title="4">BatteryDes &lt;-<span class="st"> </span>D[ <span class="kw">c</span>( <span class="st">&quot;MT&quot;</span>, <span class="st">&quot;T&quot;</span> )]</a>
<a class="sourceLine" id="cb401-5" title="5">BatteryDes</a>
<a class="sourceLine" id="cb401-6" title="6"><span class="kw">write.csv</span>(BatteryDes, <span class="dt">file =</span> <span class="st">&quot;BatteryDes.csv&quot;</span>, <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
</div>
<div id="as-vantagens-dos-delineamentos-fatoriais" class="section level3">
<h3><span class="header-section-number">4.5.2</span> As vantagens dos delineamentos fatoriais</h3>
</div>
<div id="para-casa" class="section level3">
<h3><span class="header-section-number">4.5.3</span> Para casa</h3>
<ul>
<li>Discuta as vantagens dos delineamentos fatoriais em comparação com o delineamento <em>um fator por vez</em>.
<ul>
<li>Veja Czitrom, V. “One-Factor-at-a-Time Versus Designed Experiments”. <em>The American Statistician</em>, 53:126-131, 1999.</li>
</ul></li>
</ul>
<!-- ![statcaco](images/stat_caco.gif) -->
</div>
</div>
<div id="anova-1-fator" class="section level2">
<h2><span class="header-section-number">4.6</span> ANOVA <em>1 Fator</em></h2>
</div>
<div id="delineamento-inteiramente-casualizados" class="section level2">
<h2><span class="header-section-number">4.7</span> Delineamento inteiramente casualizados</h2>
</div>
<div id="delineamento-em-blocos-ao-acaso" class="section level2">
<h2><span class="header-section-number">4.8</span> Delineamento em blocos ao acaso</h2>
</div>
<div id="fatorial" class="section level2">
<h2><span class="header-section-number">4.9</span> Fatorial</h2>
</div>
<div id="parcela-subdividida" class="section level2">
<h2><span class="header-section-number">4.10</span> Parcela subdividida</h2>

</div>
</div>
<h3>Referências</h3>
<div id="refs" class="references">
<div id="ref-lawson2014">
<p>Lawson, John. 2014. <em>Design and Analysis of Experiments with R</em>. Vol. 115. CRC press.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="visu.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="rmd.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "cerulean",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R-aplicado-a-suinocultura.pdf", "R-aplicado-a-suinocultura.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
